# Generated by Django 3.0.5 on 2020-07-31 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageManagement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
