# Generated by Django 3.0.5 on 2020-04-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BharatPe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2020-04-28')),
                ('bardate', models.DateField(default='2020-04-28')),
                ('time', models.TimeField(default='18:03:00')),
                ('numberofclient', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2020-04-28')),
                ('bardate', models.DateField(default='2020-04-28')),
                ('time', models.TimeField(default='18:03:00')),
                ('numberofclient', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Paytm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2020-04-28')),
                ('bardate', models.DateField(default='2020-04-28')),
                ('time', models.TimeField(default='18:03:00')),
                ('numberofclient', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
