# Generated by Django 3.0.5 on 2020-04-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200428_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bharatpe',
            name='time',
            field=models.TimeField(default='18:14:03'),
        ),
        migrations.AlterField(
            model_name='client',
            name='time',
            field=models.TimeField(default='18:14:03'),
        ),
        migrations.AlterField(
            model_name='paytm',
            name='time',
            field=models.TimeField(default='18:14:03'),
        ),
    ]
