# Generated by Django 3.0.5 on 2020-05-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20200501_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bharatpe',
            name='time',
            field=models.TimeField(default='06:15:28'),
        ),
        migrations.AlterField(
            model_name='client',
            name='time',
            field=models.TimeField(default='06:15:28'),
        ),
        migrations.AlterField(
            model_name='paytm',
            name='time',
            field=models.TimeField(default='06:15:28'),
        ),
    ]
