# Generated by Django 3.0.5 on 2020-05-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200501_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bharatpe',
            name='time',
            field=models.TimeField(default='07:45:16'),
        ),
        migrations.AlterField(
            model_name='client',
            name='time',
            field=models.TimeField(default='07:45:16'),
        ),
        migrations.AlterField(
            model_name='paytm',
            name='time',
            field=models.TimeField(default='07:45:16'),
        ),
    ]
