# Generated by Django 3.0.5 on 2020-05-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20200501_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bharatpe',
            name='time',
            field=models.TimeField(default='12:43:05'),
        ),
        migrations.AlterField(
            model_name='client',
            name='time',
            field=models.TimeField(default='12:43:05'),
        ),
        migrations.AlterField(
            model_name='paytm',
            name='time',
            field=models.TimeField(default='12:43:05'),
        ),
    ]
