# Generated by Django 3.0.5 on 2020-05-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20200501_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bharatpe',
            name='time',
            field=models.TimeField(default='14:28:05'),
        ),
        migrations.AlterField(
            model_name='client',
            name='time',
            field=models.TimeField(default='14:28:05'),
        ),
        migrations.AlterField(
            model_name='paytm',
            name='time',
            field=models.TimeField(default='14:28:05'),
        ),
    ]
