# Generated by Django 3.0.5 on 2020-05-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20200502_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bharatpe',
            name='time',
            field=models.TimeField(default='12:03:14'),
        ),
        migrations.AlterField(
            model_name='client',
            name='time',
            field=models.TimeField(default='12:03:14'),
        ),
        migrations.AlterField(
            model_name='paytm',
            name='time',
            field=models.TimeField(default='12:03:14'),
        ),
    ]
