# Generated by Django 3.0.5 on 2020-05-02 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20200502_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custID', models.CharField(max_length=10, null=True)),
                ('Contact_Number', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('Name', models.CharField(max_length=50, null=True)),
                ('DOB', models.DateField(default='2020-05-02')),
            ],
        ),
        migrations.AlterField(
            model_name='bharatpe',
            name='time',
            field=models.TimeField(default='16:13:27'),
        ),
        migrations.AlterField(
            model_name='client',
            name='time',
            field=models.TimeField(default='16:13:27'),
        ),
        migrations.AlterField(
            model_name='paytm',
            name='time',
            field=models.TimeField(default='16:13:27'),
        ),
    ]
