# Generated by Django 3.0.5 on 2020-05-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_auto_20200502_1613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerMembership',
            new_name='Membership',
        ),
        migrations.AlterField(
            model_name='bharatpe',
            name='time',
            field=models.TimeField(default='16:35:03'),
        ),
        migrations.AlterField(
            model_name='client',
            name='time',
            field=models.TimeField(default='16:35:03'),
        ),
        migrations.AlterField(
            model_name='paytm',
            name='time',
            field=models.TimeField(default='16:35:03'),
        ),
    ]
