# Generated by Django 3.0.5 on 2020-05-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_auto_20200502_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='Sex',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='bharatpe',
            name='bardate',
            field=models.DateField(default='2020-05-14'),
        ),
        migrations.AlterField(
            model_name='bharatpe',
            name='date',
            field=models.DateField(default='2020-05-14'),
        ),
        migrations.AlterField(
            model_name='bharatpe',
            name='time',
            field=models.TimeField(default='14:24:47'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bardate',
            field=models.DateField(default='2020-05-14'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateField(default='2020-05-14'),
        ),
        migrations.AlterField(
            model_name='client',
            name='time',
            field=models.TimeField(default='14:24:47'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='DOB',
            field=models.DateField(default='2020-05-14'),
        ),
        migrations.AlterField(
            model_name='paytm',
            name='bardate',
            field=models.DateField(default='2020-05-14'),
        ),
        migrations.AlterField(
            model_name='paytm',
            name='date',
            field=models.DateField(default='2020-05-14'),
        ),
        migrations.AlterField(
            model_name='paytm',
            name='time',
            field=models.TimeField(default='14:24:47'),
        ),
    ]
