# Generated by Django 3.0.5 on 2020-05-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_auto_20200524_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bharatpe',
            name='time',
            field=models.TimeField(default='19:31:36'),
        ),
        migrations.AlterField(
            model_name='client',
            name='time',
            field=models.TimeField(default='19:31:36'),
        ),
        migrations.AlterField(
            model_name='paytm',
            name='time',
            field=models.TimeField(default='19:31:36'),
        ),
    ]
