# Generated by Django 3.0.5 on 2020-05-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_auto_20200524_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='bharatpe',
            name='ShopID',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='ShopID',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paytm',
            name='ShopID',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bharatpe',
            name='bardate',
            field=models.DateField(default='2020-05-25'),
        ),
        migrations.AlterField(
            model_name='bharatpe',
            name='date',
            field=models.DateField(default='2020-05-25'),
        ),
        migrations.AlterField(
            model_name='bharatpe',
            name='time',
            field=models.TimeField(default='07:40:23'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bardate',
            field=models.DateField(default='2020-05-25'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateField(default='2020-05-25'),
        ),
        migrations.AlterField(
            model_name='client',
            name='time',
            field=models.TimeField(default='07:40:23'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='DOB',
            field=models.DateField(default='2020-05-25'),
        ),
        migrations.AlterField(
            model_name='paytm',
            name='bardate',
            field=models.DateField(default='2020-05-25'),
        ),
        migrations.AlterField(
            model_name='paytm',
            name='date',
            field=models.DateField(default='2020-05-25'),
        ),
        migrations.AlterField(
            model_name='paytm',
            name='time',
            field=models.TimeField(default='07:40:23'),
        ),
    ]
