# Generated by Django 3.0.5 on 2020-05-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_auto_20200525_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='bharatpe',
            name='ShopID',
            field=models.CharField(default='S1', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='ShopID',
            field=models.CharField(default='S1', max_length=10),
        ),
        migrations.AddField(
            model_name='paytm',
            name='ShopID',
            field=models.CharField(default='S1', max_length=10),
        ),
        migrations.AlterField(
            model_name='bharatpe',
            name='time',
            field=models.TimeField(default='07:51:47'),
        ),
        migrations.AlterField(
            model_name='client',
            name='time',
            field=models.TimeField(default='07:51:47'),
        ),
        migrations.AlterField(
            model_name='paytm',
            name='time',
            field=models.TimeField(default='07:51:47'),
        ),
    ]
