# Generated by Django 3.0.5 on 2020-06-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_auto_20200613_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bharatpe',
            name='time',
            field=models.TimeField(default='06:14:39'),
        ),
        migrations.AlterField(
            model_name='client',
            name='time',
            field=models.TimeField(default='06:14:39'),
        ),
        migrations.AlterField(
            model_name='paytm',
            name='time',
            field=models.TimeField(default='06:14:39'),
        ),
    ]
