# Generated by Django 3.0.5 on 2020-06-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0033_auto_20200615_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bharatpe',
            name='time',
            field=models.TimeField(default='20:47:30'),
        ),
        migrations.AlterField(
            model_name='client',
            name='time',
            field=models.TimeField(default='20:47:30'),
        ),
        migrations.AlterField(
            model_name='paytm',
            name='time',
            field=models.TimeField(default='20:47:30'),
        ),
    ]
