# Generated by Django 3.0.5 on 2020-06-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0035_auto_20200616_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bharatpe',
            name='time',
            field=models.TimeField(default='09:46:21'),
        ),
        migrations.AlterField(
            model_name='client',
            name='time',
            field=models.TimeField(default='09:46:21'),
        ),
        migrations.AlterField(
            model_name='paytm',
            name='time',
            field=models.TimeField(default='09:46:21'),
        ),
    ]
