# Generated by Django 3.0.5 on 2020-06-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0036_auto_20200616_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bharatpe',
            name='time',
            field=models.TimeField(default='09:49:59'),
        ),
        migrations.AlterField(
            model_name='client',
            name='time',
            field=models.TimeField(default='09:49:59'),
        ),
        migrations.AlterField(
            model_name='paytm',
            name='time',
            field=models.TimeField(default='09:49:59'),
        ),
    ]
