# Generated by Django 3.0.5 on 2020-07-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0037_auto_20200711_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Online',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custID', models.CharField(default='None', max_length=10)),
                ('date', models.DateField(default='2020-07-11')),
                ('employee', models.CharField(max_length=50, null=True)),
                ('ShopID', models.CharField(default='S1', max_length=10)),
                ('bardate', models.DateField(default='2020-07-11')),
                ('time', models.TimeField(default='19:47:19')),
                ('numberofclient', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='BharatPe',
        ),
        migrations.DeleteModel(
            name='Paytm',
        ),
        migrations.AlterField(
            model_name='cash',
            name='time',
            field=models.TimeField(default='19:47:19'),
        ),
    ]
