# Generated by Django 3.0.5 on 2020-06-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0038_auto_20200616_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bharatpe',
            name='time',
            field=models.TimeField(default='10:00:23'),
        ),
        migrations.AlterField(
            model_name='client',
            name='time',
            field=models.TimeField(default='10:00:23'),
        ),
        migrations.AlterField(
            model_name='paytm',
            name='time',
            field=models.TimeField(default='10:00:23'),
        ),
    ]
