# Generated by Django 3.0.5 on 2020-07-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0038_auto_20200711_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custID', models.CharField(default='None', max_length=10)),
                ('date', models.DateField(default='2020-07-12')),
                ('employee', models.CharField(max_length=50, null=True)),
                ('payment_mode', models.CharField(max_length=50, null=True)),
                ('ShopID', models.CharField(default='S1', max_length=10)),
                ('bardate', models.DateField(default='2020-07-12')),
                ('time', models.TimeField(default='13:04:58')),
                ('numberofclient', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Cash',
        ),
        migrations.DeleteModel(
            name='Online',
        ),
        migrations.AlterField(
            model_name='membership',
            name='DOB',
            field=models.DateField(default='2020-07-12'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='last_visit',
            field=models.DateField(default='2020-07-12'),
        ),
    ]
