# Generated by Django 3.0.5 on 2020-07-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0039_auto_20200712_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientvisit',
            name='visitID',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='14:40:54'),
        ),
    ]
