# Generated by Django 3.0.5 on 2020-07-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0040_auto_20200712_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientvisit',
            name='isMember',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='bardate',
            field=models.DateField(default='2020-07-17'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='date',
            field=models.DateField(default='2020-07-17'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='15:09:17'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='DOB',
            field=models.DateField(default='2020-07-17'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='last_visit',
            field=models.DateField(default='2020-07-17'),
        ),
    ]
