# Generated by Django 3.0.5 on 2020-07-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0041_auto_20200717_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientvisit',
            old_name='employee',
            new_name='employee_id',
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='bardate',
            field=models.DateField(default='2020-07-19'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='date',
            field=models.DateField(default='2020-07-19'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='16:37:50'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='DOB',
            field=models.DateField(default='2020-07-19'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='last_visit',
            field=models.DateField(default='2020-07-19'),
        ),
    ]
