# Generated by Django 3.0.5 on 2020-07-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0046_auto_20200726_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='12:27:51'),
        ),
    ]
