# Generated by Django 3.0.5 on 2020-08-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0052_auto_20200808_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='14:09:28'),
        ),
    ]
