# Generated by Django 3.0.5 on 2020-08-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0053_auto_20200808_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisit',
            name='bardate',
            field=models.DateField(default='2020-08-15'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='date',
            field=models.DateField(default='2020-08-15'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='06:04:46'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='last_visit',
            field=models.DateField(default='2020-08-15'),
        ),
    ]
