# Generated by Django 3.0.5 on 2020-08-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0054_auto_20200815_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='06:09:47'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='DOB',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
