# Generated by Django 3.0.5 on 2020-08-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0055_auto_20200815_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='08:20:31'),
        ),
    ]
