# Generated by Django 3.0.5 on 2020-08-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0057_auto_20200815_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='12:05:21'),
        ),
    ]
