# Generated by Django 3.0.5 on 2020-08-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0058_auto_20200815_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='number_of_visit',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='bardate',
            field=models.DateField(default='2020-08-21'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='date',
            field=models.DateField(default='2020-08-21'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='17:46:17'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='last_visit',
            field=models.DateField(default='2020-08-21'),
        ),
    ]
