# Generated by Django 3.0.5 on 2020-09-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0062_auto_20200904_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisit',
            name='date',
            field=models.DateField(default='2020-09-04'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='19:41:07'),
        ),
    ]
