# Generated by Django 3.0.5 on 2020-09-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0063_auto_20200904_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientvisit',
            name='bardate',
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='date',
            field=models.DateField(default='2020-09-05'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='16:27:53'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='last_visit',
            field=models.DateField(default='2020-09-05'),
        ),
    ]
