# Generated by Django 3.0.5 on 2020-09-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0066_auto_20200906_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='11:46:15'),
        ),
    ]
