# Generated by Django 3.0.5 on 2020-09-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0071_auto_20200906_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='12:10:59'),
        ),
    ]
