# Generated by Django 3.0.5 on 2020-09-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0074_auto_20200906_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='14:05:57'),
        ),
    ]
