# Generated by Django 3.0.5 on 2020-09-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0075_auto_20200906_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='14:17:54'),
        ),
    ]
