# Generated by Django 3.0.5 on 2020-09-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0081_auto_20200919_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientvisit',
            name='services',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='12:02:41'),
        ),
        migrations.AlterField(
            model_name='services',
            name='time',
            field=models.TimeField(default='12:02:41'),
        ),
    ]
