# Generated by Django 3.0.5 on 2020-09-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0082_auto_20200919_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceID', models.CharField(max_length=10, null=True)),
                ('Name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='date',
            field=models.DateField(default='2020-09-20'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='11:04:17'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='last_visit',
            field=models.DateField(default='2020-09-20'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateField(default='2020-09-20'),
        ),
        migrations.AlterField(
            model_name='services',
            name='time',
            field=models.TimeField(default='11:04:17'),
        ),
    ]
