# Generated by Django 3.0.5 on 2020-09-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0083_auto_20200920_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='Name',
            new_name='ServiceID',
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='13:37:11'),
        ),
        migrations.AlterField(
            model_name='services',
            name='time',
            field=models.TimeField(default='13:37:11'),
        ),
    ]
