# Generated by Django 3.0.5 on 2020-09-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0084_auto_20200920_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisit',
            name='date',
            field=models.DateField(default='2020-09-27'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='04:30:46'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='last_visit',
            field=models.DateField(default='2020-09-27'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateField(default='2020-09-27'),
        ),
        migrations.AlterField(
            model_name='services',
            name='time',
            field=models.TimeField(default='04:30:46'),
        ),
    ]
