# Generated by Django 3.0.5 on 2020-09-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0085_auto_20200927_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='04:55:48'),
        ),
        migrations.AlterField(
            model_name='services',
            name='time',
            field=models.TimeField(default='04:55:48'),
        ),
    ]
