# Generated by Django 3.0.5 on 2020-09-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0086_auto_20200927_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='05:15:44'),
        ),
        migrations.AlterField(
            model_name='services',
            name='time',
            field=models.TimeField(default='05:15:44'),
        ),
    ]
