# Generated by Django 3.0.5 on 2020-10-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0093_auto_20200927_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisit',
            name='date',
            field=models.DateField(default='2020-10-11'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='11:22:49'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='last_visit',
            field=models.DateField(default='2020-10-11'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateField(default='2020-10-11'),
        ),
        migrations.AlterField(
            model_name='services',
            name='time',
            field=models.TimeField(default='11:22:49'),
        ),
    ]
