# Generated by Django 3.0.5 on 2020-11-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0097_auto_20201011_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisit',
            name='date',
            field=models.DateField(default='2020-11-15'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='07:29:44'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='last_visit',
            field=models.DateField(default='2020-11-15'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateField(default='2020-11-15'),
        ),
        migrations.AlterField(
            model_name='services',
            name='time',
            field=models.TimeField(default='07:29:44'),
        ),
    ]
