# Generated by Django 3.0.5 on 2020-11-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0098_auto_20201115_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisit',
            name='date',
            field=models.DateField(default='2020-11-21'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='13:34:34'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='last_visit',
            field=models.DateField(default='2020-11-21'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateField(default='2020-11-21'),
        ),
        migrations.AlterField(
            model_name='services',
            name='time',
            field=models.TimeField(default='13:34:34'),
        ),
    ]
