# Generated by Django 3.0.5 on 2020-11-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0099_auto_20201121_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisit',
            name='date',
            field=models.DateField(default='2020-11-22'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='17:45:54'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='last_visit',
            field=models.DateField(default='2020-11-22'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateField(default='2020-11-22'),
        ),
        migrations.AlterField(
            model_name='services',
            name='time',
            field=models.TimeField(default='17:45:54'),
        ),
    ]
