# Generated by Django 3.0.5 on 2020-11-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0100_auto_20201122_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisit',
            name='time',
            field=models.TimeField(default='17:51:50'),
        ),
        migrations.AlterField(
            model_name='services',
            name='time',
            field=models.TimeField(default='17:51:50'),
        ),
    ]
