# Generated by Django 3.0.5 on 2020-05-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_userdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='mobile',
            new_name='Contact_Number',
        ),
    ]
