# Generated by Django 3.0.5 on 2020-05-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_auto_20200501_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='ownerID',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
