# Generated by Django 3.0.5 on 2020-05-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_userdetail_ownerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Contact_Number',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
