# Generated by Django 3.0.5 on 2020-11-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0006_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerregistration',
            name='shop_list',
        ),
    ]
