# Generated by Django 3.0.5 on 2020-05-01 14:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('useraccount', '0006_auto_20200501_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetail',
            new_name='OwnerRegistration',
        ),
    ]
