# Generated by Django 3.0.5 on 2020-05-01 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0007_auto_20200501_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerregistration',
            name='Contact_Number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(9999999999), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
