# Generated by Django 3.0.5 on 2020-05-02 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0008_auto_20200501_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerregistration',
            name='Contact_Number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
