# Generated by Django 3.0.5 on 2020-05-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0009_auto_20200502_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerregistration',
            name='shop_list',
            field=models.TextField(null=True),
        ),
    ]
