# Generated by Django 3.0.5 on 2020-05-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0010_ownerregistration_shop_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerregistration',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
