# Generated by Django 3.0.5 on 2020-09-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200906_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default='2020-09-19'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(default='2020-09-19'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default='2020-09-19'),
        ),
    ]
