# Generated by Django 3.0.5 on 2020-05-02 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20200502_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopID', models.CharField(max_length=10, null=True)),
                ('Desk_Contact_Number', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('Shop_Name', models.CharField(max_length=50, null=True)),
                ('Shop_Address', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
