# Generated by Django 3.0.5 on 2020-05-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_shopregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOwnerRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopID', models.CharField(max_length=10, null=True)),
                ('ownerID', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
