# Generated by Django 3.0.5 on 2020-05-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_shopownerrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default='2020-05-14'),
        ),
    ]
