# Generated by Django 3.0.5 on 2020-10-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20201011_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopregistration',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
