# Generated by Django 3.0.5 on 2020-05-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20200519_1608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopOwnerRelationship',
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default='2020-05-20'),
        ),
    ]
