# Generated by Django 3.0.5 on 2020-11-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_auto_20201121_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopregistration',
            name='owner_list',
        ),
        migrations.AddField(
            model_name='employee',
            name='access',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default='2020-11-22'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(default='2020-11-22'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default='2020-11-22'),
        ),
    ]
