# Generated by Django 3.0.5 on 2020-11-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_auto_20201122_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='access',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
