# Generated by Django 3.0.5 on 2020-05-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_auto_20200524_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='shopID',
            field=models.CharField(default='S1', max_length=10),
        ),
    ]
