# Generated by Django 3.0.5 on 2020-06-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_auto_20200525_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='ExpenseID',
            field=models.CharField(default='E1', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default='2020-06-07'),
        ),
    ]
