# Generated by Django 3.0.5 on 2020-06-21 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_auto_20200620_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeID', models.CharField(max_length=10, null=True)),
                ('ShopID', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('contact_number', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(max_length=10, null=True)),
                ('date_of_joining', models.DateField(default='2020-06-21')),
                ('DOB', models.DateField(default='2020-06-21')),
                ('temporary_address', models.TextField(max_length=1000, null=True)),
                ('permanent_address', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default='2020-06-21'),
        ),
    ]
