# Generated by Django 3.0.5 on 2020-06-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_auto_20200613_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default='2020-06-15'),
        ),
    ]
