# Generated by Django 3.0.5 on 2020-06-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_auto_20200616_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default='2020-06-17'),
        ),
    ]
