# Generated by Django 3.0.5 on 2020-07-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_auto_20200711_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DOB',
            field=models.DateField(default='2020-07-12'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(default='2020-07-12'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default='2020-07-12'),
        ),
    ]
