# Generated by Django 3.0.5 on 2020-07-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_auto_20200719_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DOB',
            field=models.DateField(default='2020-07-21'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(default='2020-07-21'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default='2020-07-21'),
        ),
    ]
