# Generated by Django 3.0.5 on 2020-07-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_auto_20200723_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_of_appointment',
        ),
        migrations.AlterField(
            model_name='employee',
            name='DOB',
            field=models.DateField(default='2020-07-26'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(default='2020-07-26'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default='2020-07-26'),
        ),
    ]
