# Generated by Django 3.0.5 on 2020-07-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0023_auto_20200726_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopregistration',
            name='Shop_Address',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
