# Generated by Django 3.0.5 on 2020-07-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0024_auto_20200726_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopregistration',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
