# Generated by Django 3.0.5 on 2020-07-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0025_shopregistration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DOB',
            field=models.DateField(default='2020-07-31'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(default='2020-07-31'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default='2020-07-31'),
        ),
    ]
