# Generated by Django 3.0.5 on 2020-08-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0026_auto_20200731_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DOB',
            field=models.DateField(default='2020-08-01'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(default='2020-08-01'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default='2020-08-01'),
        ),
        migrations.AlterField(
            model_name='shopregistration',
            name='Shop_Address',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
