# Generated by Django 3.0.5 on 2020-08-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0027_auto_20200801_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopregistration',
            name='Shop_Address',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
