# Generated by Django 3.0.5 on 2020-08-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0031_auto_20200815_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
    ]
