# Generated by Django 3.0.5 on 2020-08-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0032_remove_employee_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DOB',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
