# Generated by Django 3.0.5 on 2020-08-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0033_auto_20200815_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default='2020-08-21'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(default='2020-08-21'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default='2020-08-21'),
        ),
    ]
