# Generated by Django 3.0.5 on 2020-08-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_auto_20200801_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default='2020-08-08'),
        ),
    ]
