# Generated by Django 3.0.5 on 2020-08-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0005_auto_20200821_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default='2020-08-30'),
        ),
    ]
