# Generated by Django 3.0.5 on 2020-11-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0013_auto_20201011_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default='2020-11-15'),
        ),
    ]
