# Generated by Django 3.0.5 on 2020-11-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0015_auto_20201121_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default='2020-11-22'),
        ),
    ]
