# Generated by Django 3.0.5 on 2020-06-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='shop_id',
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
