# Generated by Django 3.0.5 on 2020-06-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='shopID',
            field=models.CharField(default='S1', max_length=10),
        ),
    ]
